services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: swe_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      # SESSION_IV: kZyBZkfMYkIqBDH7XYyM7g==
      # SESSION_KEY: akJkuWv+vX8TDABIoa0L+BwU8GKK4TuQmEmAx8QBG4g=
      # SESSION_EXPIRATION: 420
      # DUMMY: dummy
    volumes:
      # - ./backend_config/nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./ssl:/etc/nginx/ssl
      - ./backend:/Documents/SWE_Gr14/backend

  frontend:
    image: nginx:latest
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/share/nginx/html
      # - ./frontend_config/nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./ssl:/etc/nginx/ssl